export const HOME_REQUEST_START = 'HOME_REQUEST_START'
export const HOME_REQUEST_SUCCESS = 'HOME_REQUEST_SUCCESS'
export const HOME_REQUEST_FAILURE = 'HOME_REQUEST_SUCCESS'

export const DETAIL_REQUEST_START = 'DETAIL_REQUEST_START'
export const DETAIL_REQUEST_SUCCESS = 'DETAIL_REQUEST_SUCCESS'
export const DETAIL_REQUEST_FAILURE = 'DETAIL_REQUEST_FAILURE'